# Generated by Django 5.1.5 on 2025-01-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_sky", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/preview_images",
                verbose_name="Картинка превью",
            ),
        ),
    ]
