# Generated by Django 5.1.5 on 2025-01-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_sky", "0003_alter_lesson_course_alter_lesson_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание курса (необязательно).",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                help_text="Введите название курса (максимум 150 символов).",
                max_length=150,
                verbose_name="Название курса",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку для превью курса (необязательно).",
                null=True,
                upload_to="media/preview_images",
                verbose_name="Картинка превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Выберите курс, к которому относится данный урок.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web_sky.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание урока (необязательно).",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_link",
            field=models.CharField(
                blank=True,
                help_text="Добавьте ссылку на урок (необязательно).",
                null=True,
                verbose_name="Ссылка на урок",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                help_text="Введите название урока (максимум 150 символов).",
                max_length=150,
                verbose_name="Название урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку для урока (необязательно).",
                null=True,
                upload_to="media/preview_images",
                verbose_name="Картинка урока",
            ),
        ),
    ]
