# Generated by Django 5.1.5 on 2025-02-10 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_sky", "0006_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="web_sky.course",
                verbose_name="Курс",
            ),
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ManyToManyField(
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
